---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Debora Sujono"
keywords:    "Debora Sujono, Debora Utari Sujono, Debora, Utari, Sujono, UCI, UC, Irvine, ICS, machine learning"
description: "Computer Science PhD student at UC Irvine"
source_link: "https://github.com/deborausujono/deborausujono.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#aa4244'

kramdown:
  auto_ids:  false

plugins:
  - jekyll-seo-tag

